config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :card_generators
      resources :categories
      resources :descriptions
      resources :dungeons
      resources :dungeon_areas
      resources :dungeon_types
      resources :table_generators

      root to: "card_generators#index"
    end
  resources :dungeons
  resources :dungeon_types
  resources :dungeon_areas
  resources :card_generators
  get 'dashboard/index'
  resources :categories
  resources :table_generators
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dungeon.rb
class Dungeon < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :dungeon_type
  has_many   :dungeon_areas, dependent: :delete_all

  def self.generate
    params = {
      name: TableGenerator.find_by_name('Dungeon name').generate,
      situation: TableGenerator.find_by_name('Dungeon situation').generate,
      ruin: TableGenerator.find_by_name('Dungeon ruin').generate,
      entrance_condition: TableGenerator.find_by_name('Dungeon entrance').generate,
      dungeon_type: random_dungeon_type,
      size: rand(0..3)
    }
    d = Dungeon.new(params)
    d.background = d.dungeon_type.random_background
    d.detail = d.dungeon_type.random_detail
    d.generate_areas
    d.generate_diagram
    d.generate_themes
    d
  end

  # if the dungeon type or size are changed, then regenerate the dungeon areas
  def update_and_generate params
    reset_area = params[:dungeon_type_id].to_i != dungeon_type_id
    regenerate_areas = false
    regenerate_areas = true if params[:size].to_i != size || reset_area
    ret = update(params)
    if regenerate_areas
      dungeon_areas.delete_all
      generate_areas
      generate_diagram
      generate_themes
      if reset_area
        self.background = dungeon_type.random_background
        self.detail = dungeon_type.random_detail
      end
      ret = save
    end
    ret
  end

  def self.random_dungeon_type
    DungeonType.order('RANDOM()').limit(1).first
  end

  def generate_themes
    t = ''
    generator = TableGenerator.find_by_name 'Dungeon theme'
    (size+2).times do
      t << generator.generate
      t << "; "
    end
    self.themes = t
  end

  def generate_diagram
    diagram = ''
    candidates = []
    first = true
    dungeon_areas.each do |area|
      diagram << "#{area.id}[\"#{area.description}\"]\n"
      diagram << "click #{area.id} \"#{edit_dungeon_area_path(area)}\" \"Go to area\"\n"
      if first
        first = false
        diagram << "style #{area.id} fill:#9C9,stroke-width:6px\n"
      else
        diagram << "style #{area.id} fill:#f9f,stroke-width:4px\n" if area.unique
        entrances = rand(1..([3, candidates.size].min))
        entrances.times do
          connection = dungeon_type.random_connection
          target = candidates[rand(candidates.size)]
          diagram << "#{target}---|#{connection}|#{area.id}\n"
        end
      end
      candidates << area.id
      candidates.shift if candidates.size > 10
    end
    self.area_diagram = diagram
  end

  def generate_areas
    s = size
    uniq_total = [1,2 ** s + rand(s-1..s+1)].max
    uniq_total = 11 if uniq_total > 11
    uniq_count = 0
    uniq_prob = 0
    uniques = []

    while(uniq_count < uniq_total)
      area, unique = dungeon_type.generate_area uniq_prob, uniques
      if unique
        uniques << area.description
        uniq_count += 1
        uniq_prob = 0
      else
        uniq_prob += 0.15
      end
      dungeon_areas << area
      area.save
    end
  end

end

app/models/dungeon_type.rb
class DungeonType < ApplicationRecord
  def generate_area unique_prob, used_uniques
    area_desc = nil
    unique = unique_prob > rand
    if unique
      while area_desc == nil
        area_desc = random_unique_area
        area_desc = nil if used_uniques.include? area_desc
      end
    else
      area_desc = random_area
    end

#    area_desc.gsub!(/[()]/,'')

    dangers = ''

    if rand < 0.666
      dangers += TableGenerator.find_by_name("Dungeon danger").generate + "; "
    end

    discoveries = ''
    discovery_count = rand(0..3)
    discovery_count.times do
      discoveries += random_discovery + "; "
    end

    params = {
      description: area_desc,
      dangers: dangers,
      discoveries: discoveries,
      unique: unique,
      dressing: random_dressing
    }
    return DungeonArea.new(params), unique
  end

  def random_background
    Generator.table_generate backgrounds
  end

  def random_detail
    Generator.table_generate details
  end


  def random_area
    Generator.table_generate common_areas
  end

  def random_unique_area
    Generator.table_generate unique_areas
  end

  def random_connection
    Generator.table_generate connections
  end

  def random_discovery
    if rand() < 0.333
      random_feature
    else
      random_find
    end
  end

  def random_feature
    Generator.table_generate features
  end

  def random_find
    Generator.table_generate finds
  end

  def random_dressing
    Generator.table_generate dressings
  end
end

app/controllers/admin/dungeons_controller.rb
module Admin
  class DungeonsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Dungeon.
    #     page(params[:page]).
    #     per(10)
    # end
    def new
      dungeon = Dungeon.generate
      authorize_resource(dungeon)
      render locals: {
        page: Administrate::Page::Form.new(dashboard, dungeon),
      }
    end

    def update
      if requested_resource.update_and_generate(resource_params)
        redirect_to(
          [namespace, requested_resource],
          notice: translate_with_resource("update.success"),
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource),
        }
      end
    end
  end
# Define a custom finder by overriding the `find_resource` method:
# def find_resource(param)
#   Dungeon.find_by!(slug: param)
# end

# See https://administrate-prototype.herokuapp.com/customizing_controller_actions
# for more information
end

app/controllers/dungeons_controller.rb
class DungeonsController < ApplicationController
  before_action :set_dungeon, only: [:show, :edit, :update, :destroy]

  # GET /dungeons
  # GET /dungeons.json
  def index
    @dungeons = Dungeon.all
  end

  # GET /dungeons/1
  # GET /dungeons/1.json
  def show
  end

  # GET /dungeons/new
  def new
    @dungeon = Dungeon.generate
    @dungeon_type = @dungeon.dungeon_type
  end

  # GET /dungeons/1/edit
  def edit
  end

  # POST /dungeons
  # POST /dungeons.json
  def create
    @dungeon = Dungeon.new(dungeon_params)
    @dungeon.dungeon_type_id = 1

    respond_to do |format|
      if @dungeon.save
        format.html { redirect_to @dungeon, notice: 'Dungeon was successfully created.' }
        format.json { render :show, status: :created, location: @dungeon }
      else
        format.html { render :new }
        format.json { render json: @dungeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dungeons/1
  # PATCH/PUT /dungeons/1.json
  def update
    respond_to do |format|
      if @dungeon.update(dungeon_params)
        format.html { redirect_to @dungeon, notice: 'Dungeon was successfully updated.' }
        format.json { render :show, status: :ok, location: @dungeon }
      else
        format.html { render :edit }
        format.json { render json: @dungeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dungeons/1
  # DELETE /dungeons/1.json
  def destroy
    @dungeon.destroy
    respond_to do |format|
      format.html { redirect_to dungeons_url, notice: 'Dungeon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dungeon
      @dungeon = Dungeon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dungeon_params
      params.require(:dungeon).permit(:name, :size, :themes, :overview, :dungeon_type_id, :background, :detail, :situation, :entrance_condition, :ruin, :area_diagram)
    end
end

app/helpers/dungeons_helper.rb
module DungeonsHelper
end

app/views/dungeons/_form.html.erb
<%= form_with(model: dungeon, local: true) do |form| %>
  <% if dungeon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dungeon.errors.count, "error") %> prohibited this dungeon from being saved:</h2>

      <ul>
      <% dungeon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :situation %>
    <%= form.text_field :situation %>
  </div>

  <div class="field">
    <%= form.label :entrance_condition %>
    <%= form.text_field :entrance_condition %>
  </div>

  <div class="field">
    <%= form.label :ruin %>
    <%= form.text_field :ruin %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :themes %>
    <%= form.text_field :themes %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_field :overview %>
  </div>

  <div class="field">
    <%= form.label :background %>
    <%= form.text_field :background %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :area_diagram %>
    <%= form.text_area :area_diagram, size: "80x30" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dungeons/edit.html.erb
<h1>Editing Dungeon</h1>

<%= render 'form', dungeon: @dungeon %>

<%= link_to 'Show', @dungeon %> |
<%= link_to 'Back', dungeons_path %>

app/views/dungeons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dungeons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Themes</th>
      <th>Overview</th>
      <th>Dungeon type</th>
      <th>Background</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dungeons.each do |dungeon| %>
      <tr>
        <td><%= dungeon.name %></td>
        <td><%= dungeon.size %></td>
        <td><%= dungeon.themes %></td>
        <td><%= dungeon.overview %></td>
        <td><%= dungeon.dungeon_type %></td>
        <td><%= dungeon.background %></td>
        <td><%= dungeon.detail %></td>
        <td><%= link_to 'Show', dungeon %></td>
        <td><%= link_to 'Edit', edit_dungeon_path(dungeon) %></td>
        <td><%= link_to 'Destroy', dungeon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dungeon', new_dungeon_path %>

app/views/dungeons/new.html.erb
<h1>New Dungeon</h1>

<%= render 'form', dungeon: @dungeon %>

<%= link_to 'Back', dungeons_path %>

app/views/dungeons/show.html.erb
<% content_for :header do %>
  <%= javascript_include_tag 'mermaid' %>
  <%= javascript_tag do %>
    mermaid.initialize({startOnLoad:true})
  <% end %>
<% end %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dungeon.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @dungeon.size %>
</p>

<p>
  <strong>Themes:</strong>
  <%= @dungeon.themes %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @dungeon.overview %>
</p>

<p>
  <strong>Dungeon type:</strong>
  <%= @dungeon.dungeon_type.name %>
</p>

<p>
  <strong>Background:</strong>
  <%= @dungeon.background %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @dungeon.detail %>
</p>

<p>
  <strong>Areas</strong>
  <div class='mermaid'>
     graph LR
       <%= @dungeon.area_diagram %> 
  </div>
</p>

<%= link_to 'Edit', edit_dungeon_path(@dungeon) %> |
<%= link_to 'Back', dungeons_path %>