config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :card_generators
      resources :categories
      resources :descriptions
      resources :dungeons
      resources :dungeon_areas
      resources :dungeon_types
      resources :table_generators

      root to: "card_generators#index"
    end
  resources :dungeons
  resources :dungeon_types
  resources :dungeon_areas
  resources :card_generators
  get 'dashboard/index'
  resources :categories
  resources :table_generators
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/table_generator.rb
class TableGenerator < ApplicationRecord
  has_and_belongs_to_many :categories
  def generate top = true, modifier = -1
    options = []
    contents.split("\n")[0..modifier].each{|o| option, weight = o.split("*"); weight = 1 unless weight; weight.to_i.times {options << option}}
    description = roll_dice(reroll(inject_sub_generators(options[rand(options.size)])))
    #Description.create!(generator: self, description: description) if top
    description.gsub(/\r/,'')
  end

  def inject_sub_generators result
    result.gsub(/{([^{]+)}/) { |g| gen, mod = g.gsub(/{|}/,'').split(',');generator = TableGenerator.find_by_name(gen); mod = -1 unless mod; generator ? generator.generate(false, mod.to_i) : g }
  end

  def reroll result
    if result.include? '<reroll>'
      result.gsub(/<reroll>/, " & #{generate(false)}")
    else
      result
    end
  end

  def roll_dice result
    result.gsub(/\d+d\d+/) {|r| n,dice = r.split('d'); roll(n.to_i,dice.to_i)}
  end

  def roll n,d
    (1..n).map{rand(1..d)}.reduce(:+).to_s
  end
end

app/controllers/admin/table_generators_controller.rb
module Admin
  class TableGeneratorsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = TableGenerator.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   TableGenerator.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/table_generators_controller.rb
class TableGeneratorsController < ApplicationController
  before_action :set_table_generator, only: [:show, :edit, :update, :destroy]

  # GET /table_generators
  # GET /table_generators.json
  def index
    @table_generators = TableGenerator.all
  end

  # GET /table_generators/1
  # GET /table_generators/1.json
  def show
  end

  # GET /table_generators/new
  def new
    @table_generator = TableGenerator.new
  end

  # GET /table_generators/1/edit
  def edit
  end

  # POST /table_generators
  # POST /table_generators.json
  def create
    @table_generator = TableGenerator.new(table_generator_params)

    respond_to do |format|
      if @table_generator.save
        format.html { redirect_to @table_generator, notice: 'Table generator was successfully created.' }
        format.json { render :show, status: :created, location: @table_generator }
      else
        format.html { render :new }
        format.json { render json: @table_generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_generators/1
  # PATCH/PUT /table_generators/1.json
  def update
    respond_to do |format|
      if @table_generator.update(table_generator_params)
        format.html { redirect_to @table_generator, notice: 'Table generator was successfully updated.' }
        format.json { render :show, status: :ok, location: @table_generator }
      else
        format.html { render :edit }
        format.json { render json: @table_generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_generators/1
  # DELETE /table_generators/1.json
  def destroy
    @table_generator.destroy
    respond_to do |format|
      format.html { redirect_to table_generators_url, notice: 'Table generator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_generator
      @table_generator = TableGenerator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_generator_params
      p = params.require(:table_generator).permit(:name, :contents, categories: [])
      categories = []
      p[:categories].each do |c|
        if c.to_i != 0
          categories << Category.find(c.to_i)
        end
      end
      p[:categories] = categories
      p
    end
end

app/helpers/table_generators_helper.rb
module TableGeneratorsHelper
end

app/views/table_generators/_form.html.erb
<%= form_with(model: table_generator, local: true) do |form| %>
  <% if table_generator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table_generator.errors.count, "error") %> prohibited this table_generator from being saved:</h2>

      <ul>
      <% table_generator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_area :contents, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_select(:categories, Category.all, :id, :name, {prompt: 'Select'}, {multiple: true}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/table_generators/edit.html.erb
<h1>Editing Table Generator</h1>

<%= render 'form', table_generator: @table_generator %>

<%= link_to 'Show', @table_generator %> |
<%= link_to 'Back', table_generators_path %>

app/views/table_generators/index.html.erb
<h1>Table Generators</h1>

<%= link_to 'New Table Generator', new_table_generator_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @table_generators.each do |table_generator| %>
      <tr>
        <td><%= table_generator.name %></td>
        <td><%= table_generator.generate %></td>
        <td><%= link_to 'Show', table_generator %></td>
        <td><%= link_to 'Edit', edit_table_generator_path(table_generator) %></td>
        <td><%= link_to 'Destroy', table_generator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table Generator', new_table_generator_path %>

app/views/table_generators/new.html.erb
<h1>New Table Generator</h1>

<%= render 'form', table_generator: @table_generator %>

<%= link_to 'Back', table_generators_path %>

app/views/table_generators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table_generator.name %>
</p>

<p>
  <strong>Categories:</strong>
  
  <% @table_generator.categories.each do |category|%>
    <%= category.name %>
  <% end %>
    
</p>

<p>
  <strong>Results:</strong>
  <%= @table_generator.generate %>
</p>

<%= link_to 'Generate', table_generator_path(@table_generator) %> |
<%= link_to 'Edit', edit_table_generator_path(@table_generator) %> |
<%= link_to 'Back', table_generators_path %>
<p>
<%= link_to 'New Table Generator', new_table_generator_path %>
</p>