config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :card_generators
      resources :categories
      resources :descriptions
      resources :dungeons
      resources :dungeon_areas
      resources :dungeon_types
      resources :table_generators

      root to: "card_generators#index"
    end
  resources :dungeons
  resources :dungeon_types
  resources :dungeon_areas
  resources :card_generators
  get 'dashboard/index'
  resources :categories
  resources :table_generators
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dungeon_types_controller.rb
module Admin
  class DungeonTypesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = DungeonType.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   DungeonType.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/dungeon_types_controller.rb
class DungeonTypesController < ApplicationController
  before_action :set_dungeon_type, only: [:show, :edit, :update, :destroy]

  # GET /dungeon_types
  # GET /dungeon_types.json
  def index
    @dungeon_types = DungeonType.all
  end

  # GET /dungeon_types/1
  # GET /dungeon_types/1.json
  def show
  end

  # GET /dungeon_types/new
  def new
    @dungeon_type = DungeonType.new
  end

  # GET /dungeon_types/1/edit
  def edit
  end

  # POST /dungeon_types
  # POST /dungeon_types.json
  def create
    @dungeon_type = DungeonType.new(dungeon_type_params)

    respond_to do |format|
      if @dungeon_type.save
        format.html { redirect_to @dungeon_type, notice: 'Dungeon type was successfully created.' }
        format.json { render :show, status: :created, location: @dungeon_type }
      else
        format.html { render :new }
        format.json { render json: @dungeon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dungeon_types/1
  # PATCH/PUT /dungeon_types/1.json
  def update
    respond_to do |format|
      if @dungeon_type.update(dungeon_type_params)
        format.html { redirect_to @dungeon_type, notice: 'Dungeon type was successfully updated.' }
        format.json { render :show, status: :ok, location: @dungeon_type }
      else
        format.html { render :edit }
        format.json { render json: @dungeon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dungeon_types/1
  # DELETE /dungeon_types/1.json
  def destroy
    @dungeon_type.destroy
    respond_to do |format|
      format.html { redirect_to dungeon_types_url, notice: 'Dungeon type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dungeon_type
      @dungeon_type = DungeonType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dungeon_type_params
      params.require(:dungeon_type).permit(:name, :background, :detail, :backgrounds, :details, :connections, :common_areas, :unique_areas, :features, :finds, :dressings)
    end
end

app/helpers/dungeon_types_helper.rb
module DungeonTypesHelper
end

app/views/dungeon_types/_form.html.erb
<%= form_with(model: dungeon_type, local: true) do |form| %>
  <% if dungeon_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dungeon_type.errors.count, "error") %> prohibited this dungeon_type from being saved:</h2>

      <ul>
      <% dungeon_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :background %>
    <%= form.text_field :background %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :backgrounds %>
    <%= form.text_area :backgrounds, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :connections %>
    <%= form.text_area :connections, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :common_areas %>
    <%= form.text_area :common_areas, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :unique_areas %>
    <%= form.text_area :unique_areas, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :features %>
    <%= form.text_area :features, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :finds %>
    <%= form.text_area :finds, size: "80x30" %>
  </div>

  <div class="field">
    <%= form.label :dressings %>
    <%= form.text_area :dressings, size: "80x30" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dungeon_types/edit.html.erb
<h1>Editing Dungeon Type</h1>

<%= render 'form', dungeon_type: @dungeon_type %>

<%= link_to 'Show', @dungeon_type %> |
<%= link_to 'Back', dungeon_types_path %>

app/views/dungeon_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dungeon Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Background</th>
      <th>Detail</th>
      <th>Backgrounds</th>
      <th>Details</th>
      <th>Connections</th>
      <th>Common areas</th>
      <th>Unique areas</th>
      <th>Features</th>
      <th>Finds</th>
      <th>Dressings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dungeon_types.each do |dungeon_type| %>
      <tr>
        <td><%= dungeon_type.name %></td>
        <td><%= dungeon_type.background %></td>
        <td><%= dungeon_type.detail %></td>
        <td><%= dungeon_type.backgrounds %></td>
        <td><%= dungeon_type.details %></td>
        <td><%= dungeon_type.connections %></td>
        <td><%= dungeon_type.common_areas %></td>
        <td><%= dungeon_type.unique_areas %></td>
        <td><%= dungeon_type.features %></td>
        <td><%= dungeon_type.finds %></td>
        <td><%= dungeon_type.dressings %></td>
        <td><%= link_to 'Show', dungeon_type %></td>
        <td><%= link_to 'Edit', edit_dungeon_type_path(dungeon_type) %></td>
        <td><%= link_to 'Destroy', dungeon_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dungeon Type', new_dungeon_type_path %>

app/views/dungeon_types/new.html.erb
<h1>New Dungeon Type</h1>

<%= render 'form', dungeon_type: @dungeon_type %>

<%= link_to 'Back', dungeon_types_path %>

app/views/dungeon_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dungeon_type.name %>
</p>

<p>
  <strong>Background:</strong>
  <%= @dungeon_type.background %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @dungeon_type.detail %>
</p>

<p>
  <strong>Backgrounds:</strong>
  <%= @dungeon_type.backgrounds %>
</p>

<p>
  <strong>Details:</strong>
  <%= @dungeon_type.details %>
</p>

<p>
  <strong>Connections:</strong>
  <%= @dungeon_type.connections %>
</p>

<p>
  <strong>Common areas:</strong>
  <%= @dungeon_type.common_areas %>
</p>

<p>
  <strong>Unique areas:</strong>
  <%= @dungeon_type.unique_areas %>
</p>

<p>
  <strong>Features:</strong>
  <%= @dungeon_type.features %>
</p>

<p>
  <strong>Finds:</strong>
  <%= @dungeon_type.finds %>
</p>

<p>
  <strong>Dressings:</strong>
  <%= @dungeon_type.dressings %>
</p>

<%= link_to 'Edit', edit_dungeon_type_path(@dungeon_type) %> |
<%= link_to 'Back', dungeon_types_path %>